#!/usr/bin/env node
// End-to-end $RCLAW presale dry-run on Solana DEVNET. DRAFT / DEVNET-ONLY.
//
// Orchestrates the existing token/ commands through the full lifecycle with a
// GENERATED near-now timeline (deposit/claim windows open in seconds, not
// months), so create → deposit → claim can actually be exercised on devnet —
// the paths CI can't reach. Reuses genesis_presale.mjs verbatim via a
// GENESIS_CONFIG override; no presale logic is duplicated here.
//
// Modes:
//   --dry   Offline: generate the near-now config and run `presale:plan`
//           against it, print the planned sequence. No RPC, no keypair, no sends.
//   (live)  Runs keygen → create → liquidity → deposit → (wait) → claim on devnet,
//           writing a step-by-step report to token/.artifacts/e2e-report.json.
//
// Never targets mainnet (genesis_lib refuses mainnet RPCs). If the devnet faucet
// is rate-limited it logs the address to fund and stops gracefully.
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TOKEN_ROOT = path.resolve(__dirname, '..');
const ARTIFACTS = path.join(TOKEN_ROOT, '.artifacts');
const DERIVED_CONFIG = path.join(ARTIFACTS, 'dryrun.genesis.config.json');

const DRY = process.argv.includes('--dry');

// Window sizing (seconds from now). Short so the run finishes in ~a few minutes.
const OPEN_IN = 20;      // deposit window opens
const DEPOSIT_FOR = 90;  // deposit window length
const CLAIM_GAP = 20;    // gap between deposit end and TGE/claim open

function nowSec() {
  return Math.floor(Date.now() / 1000);
}
function iso(sec) {
  return new Date(sec * 1000).toISOString();
}

function log(msg) {
  console.log(`[e2e] ${msg}`);
}

// Build a near-now Genesis config from the committed one. Funding mode = mint so
// the run is self-contained (Genesis mints the supply; no separate token/ mint).
function writeDerivedConfig() {
  const base = JSON.parse(
    fs.readFileSync(path.join(TOKEN_ROOT, 'presale', 'metaplex-genesis.config.json'), 'utf8')
  );
  const t = nowSec();
  const publicStart = t + OPEN_IN;
  const depositEnd = publicStart + DEPOSIT_FOR;
  const tge = depositEnd + CLAIM_GAP;
  const cfg = {
    ...base,
    _comment: 'GENERATED near-now dry-run config — do not commit. See token/e2e/.',
    fundingMode: { ...base.fundingMode, mode: 'mint' },
    timeline: {
      _comment: 'near-now, generated by token/e2e/devnet_dryrun.mjs',
      whitelistStart: iso(t),
      publicStart: iso(publicStart),
      depositEnd: iso(depositEnd),
      tge: iso(tge),
      claimEnd: iso(tge + 365 * 86400),
    },
  };
  fs.mkdirSync(ARTIFACTS, { recursive: true });
  fs.writeFileSync(DERIVED_CONFIG, JSON.stringify(cfg, null, 2));
  return { cfg, publicStart, depositEnd, tge };
}

// Run a token/ command with the derived config active. Returns {ok, code, out}.
function run(name, args, { capture = true } = {}) {
  const env = { ...process.env, GENESIS_CONFIG: DERIVED_CONFIG };
  log(`→ ${name}: ${args.join(' ')}`);
  const res = spawnSync('node', args, {
    cwd: TOKEN_ROOT,
    env,
    encoding: 'utf8',
    stdio: capture ? 'pipe' : 'inherit',
  });
  const out = capture ? (res.stdout || '') + (res.stderr || '') : '';
  if (capture && out.trim()) console.log(out.trim());
  return { name, ok: res.status === 0, code: res.status, out: out.slice(-4000) };
}

async function sleepUntil(sec) {
  const ms = Math.max(0, sec * 1000 - Date.now()) + 2000; // +2s cushion
  if (ms > 0) {
    log(`waiting ${Math.round(ms / 1000)}s until ${iso(Math.floor((Date.now() + ms) / 1000))}…`);
    await new Promise((r) => setTimeout(r, ms));
  }
}

function saveReport(steps) {
  const report = {
    kind: 'rclaw-presale-e2e-devnet',
    mode: DRY ? 'dry' : 'live',
    generatedConfig: DERIVED_CONFIG,
    steps,
    ok: steps.every((s) => s.ok),
    note: 'DRAFT / DEVNET dry-run — see token/e2e/README.md',
  };
  fs.mkdirSync(ARTIFACTS, { recursive: true });
  const out = path.join(ARTIFACTS, 'e2e-report.json');
  fs.writeFileSync(out, JSON.stringify(report, null, 2));
  return out;
}

async function main() {
  log(`mode: ${DRY ? 'DRY (offline)' : 'LIVE (devnet)'}`);
  const { cfg: cfgBase, publicStart, depositEnd, tge } = writeDerivedConfig();
  log(`derived config: ${DERIVED_CONFIG}`);
  log(`windows → deposit ${iso(publicStart)}..${iso(depositEnd)}, claim/TGE ${iso(tge)}`);

  const steps = [];

  if (DRY) {
    // Offline: just prove the config drives the plan derivation, print sequence.
    steps.push(run('plan', ['presale/genesis_presale.mjs', 'plan']));
    log('planned live sequence: keygen → create → liquidity → deposit → (wait) → claim');
    const out = saveReport(steps);
    log(`report: ${out}`);
    process.exit(steps.every((s) => s.ok) ? 0 : 1);
  }

  // Live devnet run.
  const keygen = run('keygen', ['scripts/keygen.mjs']);
  steps.push(keygen);
  if (!keygen.ok || /rate-limited|airdrop skipped/i.test(keygen.out)) {
    log('Faucet unavailable or keygen failed — fund the printed address via https://faucet.solana.com and re-run. Stopping gracefully.');
    saveReport(steps);
    process.exit(keygen.ok ? 0 : 1);
  }

  steps.push(run('plan', ['presale/genesis_presale.mjs', 'plan']));
  steps.push(run('create', ['presale/genesis_presale.mjs', 'create']));
  steps.push(run('liquidity', ['presale/genesis_presale.mjs', 'liquidity']));

  await sleepUntil(publicStart);
  // Deposit the configured MINIMUM, not 1 SOL: keygen airdrops exactly 1 SOL,
  // so depositing 1 SOL could never cover the deposit plus rent/fees.
  const depositSol = String(cfgBase.sale?.minContributionSol ?? 0.25);
  steps.push(run('deposit', ['presale/genesis_presale.mjs', 'deposit', '--amount', depositSol]));

  await sleepUntil(tge);
  steps.push(run('claim', ['presale/genesis_presale.mjs', 'claim']));

  const out = saveReport(steps);
  const ok = steps.every((s) => s.ok);
  log(`${ok ? 'ALL STEPS OK ✓' : 'SOME STEPS FAILED ✗'} — report: ${out}`);
  process.exit(ok ? 0 : 1);
}

await main();
