"""README's command reference is the catalogue, rendered — not a second copy.

README.md carried three hand-typed command tables beside
`bot/skills/command_catalog.py`, the catalogue `/help` renders and
`tests/test_command_catalog.py` pins to the handler's registration list.
Seventy-odd rows described a hundred-plus commands; several described
behaviour the code no longer had; a "Who" column disagreed with the
catalogue's audiences. An enumerable list typed into a document is the shape
`_TOTAL_RISK_CHECKS = 23` took against an engine emitting thirty-six labels:
a second, staler copy that drifts in one direction.

The section between the markers is generated by
`scripts/render_readme_commands.py` and must equal what the script prints —
the `known_failures.txt` rule: regenerate in the same commit.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

from bot.skills.command_catalog import GROUPS, all_entries
from scripts.render_readme_commands import BEGIN, END, TARGETS, render, splice

ROOT = Path(__file__).resolve().parent.parent


@pytest.mark.parametrize("rel,lang", sorted(TARGETS.items()))
def test_the_generated_section_is_what_the_catalogue_renders(rel, lang):
    text = (ROOT / rel).read_text(encoding="utf-8")
    assert BEGIN in text and END in text, f"{rel} lost the generated-section markers"
    assert splice(text, lang) == text, (
        f"{rel} is out of date — run: python3 scripts/render_readme_commands.py")


@pytest.mark.parametrize("rel,lang", sorted(TARGETS.items()))
def test_every_registered_command_is_in_the_table_and_nothing_else_is(rel, lang):
    section = render(lang)
    rows = re.findall(r"^\| `/(\w+)` \|", section, re.MULTILINE)
    assert sorted(rows) == sorted(all_entries()), "the rendering dropped or invented a command"
    assert len(rows) == len(set(rows)), "a command is listed twice"


def test_operator_only_groups_say_so():
    section = render("en")
    for title, audience, _entries in GROUPS:
        heading = next(line for line in section.splitlines() if line.startswith(f"### {title}"))
        assert ("operator only" in heading) == (audience == "admin"), heading


@pytest.mark.parametrize("rel,header", [
    ("README.md", "| Command | Description |"),
    ("README.zh-TW.md", "| 指令 | 說明 |"),
])
def test_no_hand_typed_command_table_survives_outside_the_generated_section(rel, header):
    """The old tables, left in place beside the generated one, would be the
    drift this file exists to stop, one heading further down.

    Keyed on the TABLE HEADER, not on any row that starts with a command: the
    universe table legitimately lists `/mode` beside its instruments, and a
    row-shaped rule would have called that drift."""
    text = (ROOT / rel).read_text(encoding="utf-8")
    outside = text[:text.index(BEGIN)] + text[text.index(END) + len(END):]
    assert header not in outside, f"a hand-typed command table survives in {rel}"


def test_splice_refuses_a_readme_without_markers():
    with pytest.raises(ValueError):
        splice("# no markers here\n", "en")
