"""Ciphertext written by an OLDER cryptography must still decrypt.

Handoff open item #5's neighbour, and the reason item #2 exists: the vault is
the most valuable state on the box and its backup has never been restored. The
`cryptography` pin was held at 48.0.1 through three advisories partly because
nobody could say what a major bump would do to `secrets_vault.enc` — and
nothing in the suite could answer that, because every test encrypts and
decrypts within one process on one version. A round trip that never crosses a
version boundary cannot detect a format change.

The artifacts below were generated by **cryptography 48.0.1** and are frozen.
They are decrypted here by whatever version is installed. If a future bump
ever changes Fernet's token format, AES-GCM framing, or Ed25519/PKCS8
serialization, this file goes red BEFORE the upgrade reaches a box holding a
real vault — rather than after, when the only copy that matters will not open.

Every value is throwaway material generated for this file. The `^tests/` path
allowlist in .gitleaks.toml covers key-shaped test data; the Solana-specific
rules are deliberately NOT path-allowlisted, so a real keypair committed here
would still be caught.

Covers each primitive the codebase actually uses:

    Fernet    secrets_vault.py, exchange_credentials.py, db/models.py
    AESGCM    utils/credential_pull.py
    Ed25519   utils/attestation.py, proofofpnl/erc8004.py, token/solana_verify.py
"""
from __future__ import annotations

import base64

import pytest
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

# ── Frozen, written by cryptography 48.0.1 ────────────────────────────────
WRITTEN_BY = "48.0.1"

FERNET_KEY = "S0b3CdolvGJGGuIzeYWeoDAITFGExT9AfH-gj4LFnRk="
FERNET_TOKENS = {
    "LLM_API_KEY": "gAAAAABqdXPEWp-BDS5R-FzVDKy9pPQqX1HuwVhagqYCEtDkfzx1Bjw8Jw8YJ4aywsz5wQC4oA4L7-qiHLMemlJct0LGwK-0bTlOgRzjRA2mrgeqUZU1NpY=",
    "BITGET_SECRET": "gAAAAABqdXPE8X7BXyL1OqeICHYaQpBDLXisaZ9kHxkhnzkd-BKuekrb1cGBTA8VhrvgDYAdBaqoFsBvoAiC9EBhf8Qk__9gdQ=="
}
FERNET_PLAIN = {
    "LLM_API_KEY": "sk-not-a-real-key-000",
    "BITGET_SECRET": "also-fake-111"
}

AESGCM_KEY = "AWOU1HNQlWbQk6W2fl89Yqg2+Lfbz4wg5MFWD0suHUE="
AESGCM_NONCE = "AQEBAQEBAQEBAQEB"
AESGCM_AAD = "cnVuZWNsYXctY3JlZGVudGlhbC1wdWxs"
AESGCM_CT = "QiIRkHdfjCtSX5r5/28d98Lb6qBmIBED7MBpgRkTeIX7gpGFexY="
AESGCM_PLAIN = "credential-payload-xyz"

ED25519_PRIV_PEM = """-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIH/t4AUX6/hCYFnzhQJ+rAL2xklUIYhqmyoSQ+ZhWejX
-----END PRIVATE KEY-----"""
ED25519_PUB_RAW = "674IMR+eNuSlB3MeNSPIiU0rh/9w1Avz9eh7xXtTdtY="
ED25519_SIG = "DmfhaXEzVQe3Up4gGELpYjrzvKMcATIdzs8E0M8HQXsejVDeTsITyZaIYE90bXUnXbhMJd95aY7WFQLXSun6Aw=="
ED25519_MSG = "YXR0ZXN0YXRpb24tcGF5bG9hZC10by12ZXJpZnk="


class TestTheVaultOpensAcrossAVersionBoundary:
    """Fernet is what encrypts secrets_vault.enc and exchange_creds."""

    @pytest.mark.parametrize("name", sorted(FERNET_PLAIN))
    def test_a_48_0_1_token_still_decrypts(self, name):
        got = Fernet(FERNET_KEY.encode()).decrypt(
            FERNET_TOKENS[name].encode()).decode()
        assert got == FERNET_PLAIN[name], (
            f"a vault written by cryptography {WRITTEN_BY} no longer opens — "
            "do NOT ship this upgrade to a box holding a real vault"
        )

    def test_a_tampered_token_is_still_rejected(self):
        # The guard must not have degraded into "accepts anything".
        from cryptography.fernet import InvalidToken
        bad = FERNET_TOKENS[sorted(FERNET_TOKENS)[0]][:-4] + "AAAA"
        with pytest.raises(InvalidToken):
            Fernet(FERNET_KEY.encode()).decrypt(bad.encode())


class TestTheOtherPrimitivesSurviveToo:
    def test_aesgcm_ciphertext_from_48_0_1_decrypts(self):
        got = AESGCM(base64.b64decode(AESGCM_KEY)).decrypt(
            base64.b64decode(AESGCM_NONCE),
            base64.b64decode(AESGCM_CT),
            base64.b64decode(AESGCM_AAD)).decode()
        assert got == AESGCM_PLAIN

    def test_aesgcm_rejects_a_wrong_aad(self):
        from cryptography.exceptions import InvalidTag
        with pytest.raises(InvalidTag):
            AESGCM(base64.b64decode(AESGCM_KEY)).decrypt(
                base64.b64decode(AESGCM_NONCE),
                base64.b64decode(AESGCM_CT), b"wrong-aad")

    def test_an_ed25519_signature_from_48_0_1_verifies(self):
        Ed25519PublicKey.from_public_bytes(
            base64.b64decode(ED25519_PUB_RAW)).verify(
                base64.b64decode(ED25519_SIG), base64.b64decode(ED25519_MSG))

    def test_ed25519_still_rejects_a_bad_signature(self):
        from cryptography.exceptions import InvalidSignature
        with pytest.raises(InvalidSignature):
            Ed25519PublicKey.from_public_bytes(
                base64.b64decode(ED25519_PUB_RAW)).verify(
                    base64.b64decode(ED25519_SIG), b"a different message")

    def test_a_pkcs8_private_key_from_48_0_1_still_loads(self):
        sk = serialization.load_pem_private_key(
            ED25519_PRIV_PEM.encode(), password=None)
        raw = sk.public_key().public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw)
        assert base64.b64encode(raw).decode() == ED25519_PUB_RAW
