"""Three keys protect three stores, and the product must say which is which.

The operator's report was "WEB_CREDS_KEY is unset, so that Bybit key remains
in plaintext". The first half is a fact; the "so" was the product's fault.
`boot_health.py` described WEB_CREDS_KEY as "decrypting stored per-user
exchange keys", so the boot WARNING that names it read as "the keys users
linked are sitting unencrypted". They are not:

  * keys users link (/connect, the website)  → Fernet under the MASTER key,
                                               whatever else is set;
  * a website submission in transit to the bot → SEALED to this bot's own key,
                                               or refused (nothing is queued);
  * the operator's own venue keys            → .env, mirrored encrypted into
                                               the vault; the .env copy stays
                                               until it is set through
                                               /setexchange and deleted.

The third line is where a Bybit key really can remain in the clear, and it
has nothing to do with WEB_CREDS_KEY. So: the boot line now prints the effect
beside the name, /vault says what encrypts what, and /setexchange takes Bybit
and BingX so the .env copy can be retired (tests/test_setexchange_admin.py).

THE SECOND LINE CHANGED THE FOLLOWING WEEK, and it changed what this file has
to hold. The report behind it was the other half of the same complaint — the
website's connect form did not save anything — and the cause was that
WEB_CREDS_KEY had to be generated by hand and set in TWO deployments before a
submission could be protected at all. It is sealed to the bot's own published
key now (`bot/utils/creds_sealing.py`), with nothing to configure. So the
honest thing to say about that variable is no longer "a surface is broken"; it
is that it is legacy and unset is the ordinary state. A warning that names a
surface which is in fact working is how an operator learns to skip the next
warning — the same misreading, one door along.
"""
from __future__ import annotations

from types import SimpleNamespace

import pytest

from bot.core import boot_health as bh

# ── the boot line ──────────────────────────────────────────────────────────

def test_every_important_variable_states_its_effect():
    for name in bh.IMPORTANT_ENV:
        assert name in bh.IMPORTANT_ENV_EFFECT and bh.IMPORTANT_ENV_EFFECT[name].strip(), name


def test_the_boot_line_prints_the_effect_beside_the_name():
    msg = bh.format_preflight(bh.env_preflight({"TELEGRAM_BOT_TOKEN": "t" * 40}))
    for name, effect in bh.IMPORTANT_ENV_EFFECT.items():
        assert f"{name} — {effect}" in msg, name


def test_the_legacy_shared_key_is_not_reported_as_a_broken_surface():
    """An unset WEB_CREDS_KEY breaks nothing on the connect form any more, so
    the boot line must not list it. Listing it would be the 2026-09-06
    misreading in a milder form: a name printed under "a web surface will be
    degraded" for a surface that works."""
    assert "WEB_CREDS_KEY" not in bh.IMPORTANT_ENV
    assert "WEB_CREDS_KEY" not in bh.IMPORTANT_ENV_EFFECT
    msg = bh.format_preflight(bh.env_preflight({"TELEGRAM_BOT_TOKEN": "t" * 40}))
    assert "WEB_CREDS_KEY" not in msg


def test_the_variable_the_connect_form_actually_needs_says_so():
    """Something still gates it — the SYNC CHANNEL, which is what carries the
    bot's sealing key to the website. Dropping the old line without naming its
    replacement would leave the one variable that can turn the form off
    described as a dashboard concern."""
    effect = bh.IMPORTANT_ENV_EFFECT["BOT_SYNC_SECRET"]
    assert "connect form" in effect and "sealing key" in effect
    assert "stored per-user" not in effect, "the 2026-09-06 misreading, back"


# ── /vault ─────────────────────────────────────────────────────────────────

def _vault_host(sent):
    from bot.skills.telegram_handler import TelegramHandler
    h = TelegramHandler.__new__(TelegramHandler)

    async def _send(update, text, *a, **k):
        sent.append(str(text))

    h._send = _send
    h._is_admin = lambda update: True
    return h


def _status(web_creds_env: bool):
    keys = ("BITGET_API_KEY", "BITGET_API_SECRET", "BITGET_PASSPHRASE",
            "TELEGRAM_BOT_TOKEN", "WEB_GATEWAY_SECRET", "BOT_SYNC_SECRET",
            "WEB_CREDS_KEY", "BYBIT_API_KEY", "BYBIT_API_SECRET")
    st = {k: {"env": True, "vault": True} for k in keys}
    st["WEB_CREDS_KEY"] = {"env": web_creds_env, "vault": False}
    st["BYBIT_API_KEY"] = {"env": True, "vault": False}     # .env only
    st["BYBIT_API_SECRET"] = {"env": True, "vault": False}
    return st


@pytest.fixture()
def sealing_statedir(tmp_path, monkeypatch):
    """/vault reads the sealing key's fingerprint, and reading it GENERATES the
    key on a first boot. Point that at a throwaway directory so a test run does
    not write one into the repo's real data/."""
    import bot.utils.creds_sealing as cs
    monkeypatch.setenv("RUNECLAW_STATE_DIR", str(tmp_path))
    cs._cache.clear()
    yield tmp_path
    cs._cache.clear()


@pytest.mark.asyncio
@pytest.mark.parametrize("web_set", [False, True])
async def test_vault_says_what_encrypts_what(monkeypatch, sealing_statedir, web_set):
    import bot.core.secrets_vault as sv
    import bot.utils.creds_sealing as cs
    monkeypatch.setattr(sv, "vault_status", lambda: _status(web_set))
    sent = []
    h = _vault_host(sent)
    await h._cmd_vault(SimpleNamespace(effective_user=SimpleNamespace(id=1)),
                       SimpleNamespace(args=[]))
    card = sent[-1]
    assert "What encrypts what" in card
    assert "master key" in card and "RUNECLAW_SECRETS_KEY" in card
    # The website line names the key submissions are actually sealed to, by
    # fingerprint. A card that says "sealed" without saying to WHAT is the
    # unattributable reading this repo keeps finding: true, and unusable for
    # deciding whether the website is talking to this bot.
    assert "sealed to this bot's own key" in card
    assert cs.kid() in card
    assert "the website cannot read what it stores" in card
    assert "WEB_CREDS_KEY" in card
    if web_set:
        assert "is set" in card
        assert "legacy" in card
    else:
        assert "is unset" in card
        assert "not needed" in card, (
            "an unset legacy key must read as NOT NEEDED, not as 'stored in the clear' "
            "and not as a broken form")
        assert "already linked are unaffected" in card
    # The Bybit key that is only in .env is named as env-only, with its path out.
    assert "BYBIT_API_KEY" in card
    assert "/setexchange" in card
    assert "does not replace it" in card, (
        "the card must say the vault mirrors .env — that is where a key stays in the clear")


@pytest.mark.asyncio
async def test_vault_says_so_when_the_sealing_key_cannot_be_read(
        monkeypatch, sealing_statedir):
    """UNREADABLE IS NOT SEALED. If the key file cannot be read the connect
    form is refusing submissions, and the card that an operator opens to find
    that out must not print the green line describing the working case."""
    import bot.core.secrets_vault as sv
    import bot.utils.creds_sealing as cs
    monkeypatch.setattr(sv, "vault_status", lambda: _status(False))

    def _boom():
        raise OSError("permission denied")

    monkeypatch.setattr(cs, "kid", _boom)
    sent = []
    h = _vault_host(sent)
    await h._cmd_vault(SimpleNamespace(effective_user=SimpleNamespace(id=1)),
                       SimpleNamespace(args=[]))
    card = sent[-1]
    assert "could not be read" in card
    assert "refuses" in card
    assert "sealed to this bot's own key" not in card


@pytest.mark.asyncio
async def test_vault_points_the_bybit_key_at_its_own_command(monkeypatch, sealing_statedir):
    """A Bybit key missing from BOTH env and vault used to be hidden, and a
    present one had no command to point at. It has one now."""
    import bot.core.secrets_vault as sv
    st = _status(True)
    st["BYBIT_API_KEY"] = {"env": True, "vault": False}
    monkeypatch.setattr(sv, "vault_status", lambda: st)
    sent = []
    h = _vault_host(sent)
    await h._cmd_vault(SimpleNamespace(effective_user=SimpleNamespace(id=1)),
                       SimpleNamespace(args=[]))
    assert "/setexchange bybit" in sent[-1]


# ── the website half: unset means refused, never plaintext ─────────────────

def _submit_handler_code() -> str:
    """`POST /api/credentials`, comments stripped.

    Stripped because the handler's own comments name `sealJSON` and
    `encryptJSON` in prose — the standing rule, and this scan would otherwise
    find the explanation and read it as the code.
    """
    from pathlib import Path

    from tests.source_scan import js_code_only
    route = js_code_only(Path("app/routes/credentials.js").read_text(encoding="utf-8"))
    i = route.index("router.post('/'")
    return route[i:route.index("router.delete('/'", i)]


def test_the_website_refuses_rather_than_queues_what_nobody_can_open():
    """Pinned from the Node side by reading, because the claim on the /vault
    card ("the website's connect form refuses until it can") is only true
    while this holds — and it is a claim made in Python about JavaScript.

    WIRING ONLY, deliberately. The behaviour — the 503, its reason code, the
    absence of a queued row — is exercised end to end in
    `app/test/creds_sealing.test.js`. What a source scan adds is the ORDER: the
    gate must be reached before anything is protected, which is the property
    that decides whether a submission can be stored under a path the gate did
    not approve.
    """
    body = _submit_handler_code()
    gate = body.index("await protection()")
    assert "prot.mode === 'off'" in body
    assert "503" in body[gate:][:400]
    # Nothing is protected — by either path — before the gate has answered.
    for fn in ("sealJSON(", "encryptJSON("):
        assert gate < body.index(fn), f"{fn} is reachable before the gate"


def test_the_two_protections_are_a_choice_not_a_fallback_after_failure():
    """`sealJSON` must not be wrapped in a try that drops to the shared key.

    That is the shape this would most plausibly grow — "seal if we can, else
    encrypt" reads like resilience — and it would silently store a submission
    under weaker protection than the status endpoint just advertised, on the
    one deployment where the sealed path is broken and nobody is looking.
    """
    body = _submit_handler_code()
    seal = body.index("sealJSON(")
    tail = body[body.index("const payload"):]
    assert "prot.mode === 'sealed'" in tail[:200], (
        "which protection is used must be decided by the mode the gate returned")
    assert "catch" not in body[body.index("const payload"):seal + 200], (
        "a catch around the seal would make the shared key a silent fallback")
