"""The logo is one contour, and every surface that draws it draws THAT one.

RUNECLAW's mark appears on seven surfaces: two favicons, the platform's sprite
symbol, the marketing site's inline header wordmark, and three PNG app icons
(one of which the SPL token metadata points at). Before this, three of them
were drawn by different hands — the platform favicon and the sprite used a
Unicode text glyph set in Georgia, the marketing site drew a hexagon with a
stroked "R" inside it — so "the logo" was already two different drawings, and
nothing could see that from inside either file.

`scripts/brand_mark.py` holds the contour and emits all of them. This drives
`path_d()` and asserts each committed VECTOR surface carries exactly it, so a
hand-edit to any one of them fails here rather than shipping a second logo.

WHAT THIS DOES NOT CHECK, stated rather than implied: the three PNGs are
generated by the same module from the same contour, and are NOT re-derived
here. Rasterising 1024x1024 in pure Python is a minute per icon, not
milliseconds. Regenerate them with `python3 scripts/brand_mark.py` when the
contour changes; a gate that claimed to check them would be a gate whose
coverage is overstated, which is the failure CLAUDE.md exists to prevent.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))

import brand_mark  # noqa: E402

# Every file that DRAWS the mark as vectors, and what each one needs beyond the
# `d` — a filled contour with a hole renders as a solid blob without evenodd,
# which is the one way to carry the right path and still show the wrong logo.
VECTOR_SURFACES = (
    ("app/public/favicon.svg", 'fill-rule="evenodd"'),
    ("site/public/favicon.svg", 'fill-rule="evenodd"'),
    ("app/public/js/icons.js", 'fill-rule="evenodd"'),
    ("site/src/routes/__root.tsx", 'fillRule="evenodd"'),   # JSX spells it camelCase
)

PNG_SURFACES = (
    "app/public/app_icon_256.png",
    "app/public/app_icon_512.png",
    "app/public/app_icon_1024.png",
    "website/app_icon_256.png",
    "website/app_icon_512.png",
)


@pytest.mark.parametrize("rel,evenodd", VECTOR_SURFACES)
def test_every_vector_surface_carries_the_generated_contour(rel, evenodd):
    src = (REPO / rel).read_text()
    assert brand_mark.path_d() in src, (
        f"{rel} does not carry scripts/brand_mark.path_d(). Either it was "
        f"hand-edited — which makes it a second logo — or the contour moved "
        f"and nobody re-ran `python3 scripts/brand_mark.py`."
    )
    assert evenodd in src, (
        f"{rel} draws the contour without {evenodd}. The bowl is a HOLE in the "
        f"outer contour; without the even-odd rule it fills solid and the mark "
        f"renders as a blob."
    )


def test_the_bowl_is_actually_a_hole():
    """The reason evenodd is load-bearing, driven rather than asserted in prose.

    A point inside the counter must be OUTSIDE the mark. If somebody 'simplifies'
    the contour into two separate filled shapes this fails, and it fails for the
    reason the icon would look wrong.
    """
    # Centre of the counter ring, well clear of every edge.
    assert not brand_mark.inside(16.0, 10.0), "the bowl's counter filled in"
    # Two points that must be solid: the stem, and the leg.
    assert brand_mark.inside(11.0, 16.0), "the stem is not filled"
    assert brand_mark.inside(19.5, 24.0), "the leg is not filled"


def test_the_mark_is_not_a_text_glyph():
    """What this replaced, pinned so it cannot come back.

    A glyph a font does not carry renders as tofu — no error, no warning, and
    only on machines nobody tested on. Both the favicon and the sprite symbol
    drew the brand this way.
    """
    for rel, _ in VECTOR_SURFACES:
        src = (REPO / rel).read_text()
        assert "<text" not in src, f"{rel} draws the brand as text again"


def test_the_favicons_are_byte_identical():
    """Two files, one emitter. They are written from `favicon_svg()` in the same
    pass, so a difference means one of them was edited by hand."""
    a = (REPO / "app/public/favicon.svg").read_text()
    b = (REPO / "site/public/favicon.svg").read_text()
    assert a == b, "the platform and marketing favicons have diverged"
    assert a == brand_mark.favicon_svg(), "a favicon was edited by hand"


def test_the_sprite_symbol_is_what_the_module_emits():
    src = (REPO / "app/public/js/icons.js").read_text()
    assert brand_mark.brand_symbol_svg() in src


def test_the_sprite_symbol_takes_its_colour_from_the_brand_rule():
    """`.brand .brand-mark` sets `color: var(--gold)` and a drop-shadow halo.
    A symbol that hard-codes a fill ignores both, so the mark stops re-theming
    with the palette — which `styles.css` documents as the whole point of the
    token names."""
    symbol = brand_mark.brand_symbol_svg()
    assert 'fill="currentColor"' in symbol
    css = (REPO / "app/public/styles.css").read_text()
    assert ".brand .brand-mark" in css and "color: var(--gold)" in css


def test_every_png_surface_is_an_opaque_png():
    """Not a check of their CONTENT — see the module docstring. What a cheap
    read of the header CAN see is the two things that break a consumer outright.

    A missing file: the web manifest, the apple-touch-icon link and the SPL
    token metadata each name one of these by path.

    An alpha channel: the Farcaster mini-app spec refuses an icon that has one,
    and `app/test/farcaster_manifest.test.js` reads the same byte out of the
    1024. The first draft of the rasteriser wrote RGBA and that test caught it —
    this asserts it for the whole set rather than the one file a different
    spec happens to police.
    """
    for rel in PNG_SURFACES:
        p = REPO / rel
        assert p.exists(), f"{rel} is missing"
        data = p.read_bytes()
        assert data[:8] == b"\x89PNG\r\n\x1a\n", f"{rel} is not a PNG"
        colour_type = data[25]      # IHDR: 8 sig + 8 len/tag + w(4) + h(4) + depth(1)
        assert colour_type == 2, (
            f"{rel} is PNG colour type {colour_type}; 2 is RGB and 6 (RGBA) is "
            f"refused by the Farcaster icon spec. Nothing here is transparent."
        )


def test_the_two_website_icons_are_the_platform_icons():
    """`website/` is served straight out of the checkout and holds its own copy
    of the two icons the prerender references. Two copies is two answers unless
    something compares them."""
    for size in (256, 512):
        a = (REPO / f"app/public/app_icon_{size}.png").read_bytes()
        b = (REPO / f"website/app_icon_{size}.png").read_bytes()
        assert a == b, f"website/app_icon_{size}.png is not app/public's"


# ── the box the mark is drawn INTO ──────────────────────────────────────────
#
# Carrying the right contour is not the same as rendering it at the right size,
# and the two surfaces have opposite needs. A favicon and an app icon are square
# canvases where the padding IS the design. A wordmark sits beside 17px type,
# where a square box around a 13.1 x 24 letterform is 45% glyph and 55% gap —
# which reads as the mark having come loose from the word. The mark that was
# here before was a 25-wide disc and filled a square; a letterform does not, so
# this could not have been noticed by carrying the old sizing forward.

TEXT_ADJACENT = ("app/public/js/icons.js", "site/src/routes/__root.tsx")
STANDALONE = ("app/public/favicon.svg", "site/public/favicon.svg")


@pytest.mark.parametrize("rel", TEXT_ADJACENT)
def test_a_mark_set_beside_text_is_cropped_to_the_contour(rel):
    src = (REPO / rel).read_text()
    assert f'viewBox="{brand_mark.viewbox_tight()}"' in src, (
        f"{rel} draws the mark in a box that is not the contour's own. Derive "
        f"it from `brand_mark.viewbox_tight()` — a viewBox typed by hand is a "
        f"second answer about where the mark's edges are."
    )


@pytest.mark.parametrize("rel", STANDALONE)
def test_a_standalone_icon_keeps_the_square_canvas(rel):
    src = (REPO / rel).read_text()
    assert 'viewBox="0 0 32 32"' in src, (
        f"{rel} is a square canvas — cropping it to the contour would produce a "
        f"favicon with no margin and an app icon that fails the maskable safe zone."
    )


def test_the_css_box_has_the_marks_aspect():
    """`.brand .brand-mark` sets width and height in pixels, so the element's
    box is a third statement about the mark's shape beside the viewBox and the
    contour. If it disagrees, SVG letterboxes and the gap comes straight back —
    silently, because `preserveAspectRatio` defaults to fitting rather than to
    complaining."""
    import re
    css = (REPO / "app/public/styles.css").read_text()
    rule = re.search(r"\.brand \.brand-mark \{([^}]*)\}", css)
    assert rule, ".brand .brand-mark rule not found"
    w = re.search(r"width:\s*([\d.]+)px", rule.group(1))
    h = re.search(r"height:\s*([\d.]+)px", rule.group(1))
    assert w and h, "the brand mark box is not sized in px"
    _, _, bw, bh = brand_mark.bbox()
    want = bw / bh
    got = float(w.group(1)) / float(h.group(1))
    assert abs(got - want) < 0.03, (
        f".brand .brand-mark is {w.group(1)}x{h.group(1)} (ratio {got:.3f}) but "
        f"the contour's is {want:.3f} — the mark will letterbox inside its own box."
    )
