"""The bot's half of the sealed credential path.

WHAT THIS REPLACED. Submitting exchange API keys on the website required
``WEB_CREDS_KEY``: 32 random bytes an operator generated by hand and then set
IDENTICALLY in two deployments' environments. Until both were set the connect
form answered 503 — the operator's report on 2026-09-06 was, in effect, "the
form does not save". It also gave the website a key it never needed: the site
could read back every submission it stored.

The bot owns a keypair now. It generates one on first use, publishes the PUBLIC
half over the sync channel it already authenticates on, and the website seals
each submission to it. Nothing is configured by hand and the website cannot
open what it stores.

These drive ``bot/utils/creds_sealing.py`` directly. The REAL Node sealer is
run against ``unseal`` in ``tests/test_creds_envelope_cross_runtime.py`` — the
two answer different questions, and a Python-only round trip agreeing with
itself is exactly the failure that file was written about.
"""

from __future__ import annotations

import base64
import json
import os
import stat

import pytest

import bot.utils.creds_sealing as cs


@pytest.fixture()
def statedir(tmp_path, monkeypatch):
    """A throwaway state dir, so no test ever writes a key into real data/."""
    monkeypatch.setenv("RUNECLAW_STATE_DIR", str(tmp_path))
    cs._cache.clear()
    yield tmp_path
    cs._cache.clear()


def _seal(obj: dict, pem: str, kid: str | None = None, alg: str | None = None) -> dict:
    """Seal the way app/lib/creds_crypto.js does — a local mirror.

    Only for driving the failure cases below (a wrong kid, a tampered tag) that
    the real Node sealer will not produce on purpose. The HAPPY path is proved
    against the shipped Node sealer in the cross-runtime file, because a mirror
    that agrees with the code it mirrors proves nothing about the code.
    """
    return _seal_raw(obj, pem, kid=kid, alg=alg)


def _seal_raw(payload, pem: str, kid: str | None = None, alg: str | None = None) -> dict:
    """The same, over any JSON value — the sealer's own signature takes an
    object, so a non-object payload can only be built here."""
    import os as _os

    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import padding
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    pub = serialization.load_pem_public_key(pem.encode())
    content_key = _os.urandom(32)
    iv = _os.urandom(12)
    blob = AESGCM(content_key).encrypt(iv, json.dumps(payload).encode(), None)
    ct, tag = blob[:-16], blob[-16:]
    ek = pub.encrypt(content_key, padding.OAEP(
        mgf=padding.MGF1(algorithm=hashes.SHA256()),
        algorithm=hashes.SHA256(), label=None))
    b64 = lambda b: base64.b64encode(b).decode()   # noqa: E731
    return {"v": 2, "alg": alg or cs.SEAL_ALG, "kid": kid or cs.kid(),
            "ek": b64(ek), "iv": b64(iv), "tag": b64(tag), "ct": b64(ct)}


class TestTheKeyFile:
    def test_a_key_that_cannot_be_read_raises_its_OWN_exception(self, statedir):
        """Not a bare OSError, and not the same error a stale kid gives. The
        puller acks one and leaves the other queued, and getting that backwards
        throws away a user's submitted keys."""
        path = cs.private_key_path()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("this is not a PEM")
        cs._cache.clear()
        with pytest.raises(cs.SealingKeyUnavailable):
            cs.load_or_create_private_key()

    def test_generated_on_first_use_and_never_world_readable(self, statedir):
        path = cs.private_key_path()
        assert not path.exists()
        cs.load_or_create_private_key()
        assert path.exists()
        mode = stat.S_IMODE(os.stat(path).st_mode)
        assert mode == 0o600, f"private key is mode {mode:o}"
        # No stray temp file left behind holding the same bytes.
        assert not list(statedir.glob("*.tmp"))

    def test_the_same_key_is_reused_across_calls(self, statedir):
        first = cs.public_key_pem()
        cs._cache.clear()                     # force a re-read from disk
        assert cs.public_key_pem() == first

    def test_a_lost_key_file_becomes_a_new_key_not_a_crash(self, statedir):
        old = cs.kid()
        cs.private_key_path().unlink()
        cs._cache.clear()
        new = cs.kid()
        assert new != old
        # And the change is visible to the publisher, which is what gets the
        # website off the key it can no longer reach.
        assert cs.public_key_record()["kid"] == new

    def test_the_private_half_is_not_in_what_we_publish(self, statedir):
        rec = cs.public_key_record()
        assert "PRIVATE" not in rec["pem"]
        assert rec["pem"].startswith("-----BEGIN PUBLIC KEY-----")
        assert rec["alg"] == cs.SEAL_ALG
        assert rec["kid"] == cs.kid()


class TestKid:
    def test_is_sixteen_hex_of_the_spki_digest(self, statedir):
        import hashlib

        from cryptography.hazmat.primitives import serialization
        der = serialization.load_pem_public_key(
            cs.public_key_pem().encode()).public_bytes(
                serialization.Encoding.DER,
                serialization.PublicFormat.SubjectPublicKeyInfo)
        assert cs.kid() == hashlib.sha256(der).hexdigest()[:16]
        assert len(cs.kid()) == 16

    def test_hashes_the_key_not_the_text_carrying_it(self, statedir):
        """PEM is not canonical. A fingerprint that moved with line breaks
        would disagree with the website for a reason that has nothing to do
        with the key — and the mismatch message would send the reader hunting
        for a rotation that never happened."""
        from cryptography.hazmat.primitives import serialization
        pub = serialization.load_pem_public_key(cs.public_key_pem().encode())
        der = pub.public_bytes(serialization.Encoding.DER,
                               serialization.PublicFormat.SubjectPublicKeyInfo)
        assert cs.kid(der) == cs.kid()


class TestUnseal:
    def test_round_trip(self, statedir):
        creds = {"venue": "bybit", "api_key": "AK", "api_secret": "SEC"}
        assert cs.unseal(_seal(creds, cs.public_key_pem())) == creds

    def test_accepts_the_envelope_as_a_json_string_too(self, statedir):
        """The pending row arrives as TEXT from the website's database."""
        env = json.dumps(_seal({"api_key": "AK"}, cs.public_key_pem()))
        assert cs.unseal(env)["api_key"] == "AK"

    def test_refuses_a_v1_envelope_rather_than_guessing(self, statedir):
        with pytest.raises(ValueError, match="sealed"):
            cs.unseal({"v": 1, "iv": "AA", "tag": "AA", "ct": "AA"})

    def test_refuses_an_algorithm_it_does_not_implement(self, statedir):
        env = _seal({"api_key": "AK"}, cs.public_key_pem(), alg="rot13")
        with pytest.raises(ValueError, match="algorithm"):
            cs.unseal(env)

    def test_a_stale_kid_is_named_not_surfaced_as_a_padding_error(self, statedir):
        """The website sealing to a key this bot no longer holds is a REAL
        state — a wiped data/ regenerates the key — and it has a remedy the
        message states. A bare OAEP failure would read as corruption."""
        env = _seal({"api_key": "AK"}, cs.public_key_pem(), kid="0" * 16)
        with pytest.raises(ValueError, match="republished"):
            cs.unseal(env)

    def test_a_tampered_ciphertext_fails_it_does_not_open(self, statedir):
        env = _seal({"api_key": "AK"}, cs.public_key_pem())
        ct = bytearray(base64.b64decode(env["ct"]))
        ct[0] ^= 0xFF
        env["ct"] = base64.b64encode(bytes(ct)).decode()
        with pytest.raises(Exception):
            cs.unseal(env)

    def test_a_malformed_envelope_says_so(self, statedir):
        with pytest.raises(ValueError, match="malformed"):
            cs.unseal({"v": 2, "alg": cs.SEAL_ALG, "kid": cs.kid(), "ek": "AA"})

    def test_a_payload_that_is_not_an_object_is_refused_here(self, statedir):
        """It opens perfectly and then fails three frames away, inside
        `creds.get("venue")`, as an AttributeError the puller logs as a
        'processing error'. The format is known here; say so here."""
        env = _seal({"api_key": "AK"}, cs.public_key_pem())
        env2 = _seal_raw("just a string", cs.public_key_pem())
        assert cs.unseal(env)["api_key"] == "AK"
        with pytest.raises(ValueError, match="not an object"):
            cs.unseal(env2)

    def test_a_wrapped_key_of_the_wrong_size_is_refused(self, statedir):
        """A 32-byte content key is the format. Accepting whatever RSA returned
        and handing it to AESGCM would turn a format disagreement into an
        exception from a library three layers down."""
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import padding
        env = _seal({"api_key": "AK"}, cs.public_key_pem())
        pub = serialization.load_pem_public_key(cs.public_key_pem().encode())
        short = pub.encrypt(b"\x01" * 16, padding.OAEP(
            mgf=padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(), label=None))
        env["ek"] = base64.b64encode(short).decode()
        with pytest.raises(ValueError, match="32 bytes"):
            cs.unseal(env)


class TestThePullerUsesIt:
    def test_decrypt_payload_routes_v2_to_the_seal(self, statedir, monkeypatch):
        """The two envelopes share one entry point, and the version picks the
        path. A v2 row falling through to the shared-key branch would raise
        'WEB_CREDS_KEY missing' — a config error for a row that needs no
        config, which is the wrong thing to tell an operator."""
        import bot.utils.credential_pull as cp
        monkeypatch.delenv("WEB_CREDS_KEY", raising=False)
        env = json.dumps(_seal({"api_key": "AK", "api_secret": "S"}, cs.public_key_pem()))
        assert cp.decrypt_payload(env)["api_key"] == "AK"

    def test_the_pull_needs_no_shared_key_at_all(self, statedir, monkeypatch):
        """The gate moved: it is the sync channel, not a hand-set secret. This
        is the whole user-visible change — the form works with nothing in
        either .env beyond what pairing the website already needs."""
        import bot.utils.credential_pull as cp
        monkeypatch.delenv("WEB_CREDS_KEY", raising=False)
        monkeypatch.setattr(cp, "SYNC_SECRET", "s" * 48)
        assert cp.is_configured() is True
        monkeypatch.setattr(cp, "SYNC_SECRET", "")
        assert cp.is_configured() is False

    def test_a_sealed_row_imports_into_the_store(self, statedir, monkeypatch):
        import bot.utils.credential_pull as cp
        monkeypatch.delenv("WEB_CREDS_KEY", raising=False)

        class _Store:
            def __init__(self):
                self.creds = {}

            def set(self, tg, k, s, p):
                self.creds[str(tg)] = (k, s, p)

        store = _Store()
        row = {"user_id": 1, "telegram_id": "999", "action": "connect",
               "encrypted_payload": json.dumps(_seal(
                   {"api_key": "AK", "api_secret": "SEC", "passphrase": "PP"},
                   cs.public_key_pem()))}
        acks = cp.process_pending([row], store)
        assert store.creds["999"] == ("AK", "SEC", "PP")
        assert acks == [{"user_id": 1, "action": "connect", "ok": True}]

    def test_an_unreadable_key_file_leaves_the_row_QUEUED_not_acked(
            self, statedir, monkeypatch):
        """THE ONE THAT DESTROYS SUBMISSIONS IF IT IS WRONG.

        Acking clears the row on the website. A row this bot cannot open right
        now — its key file unreadable — is openable a moment later, so acking
        it throws away keys the user typed correctly and tells them the
        connection failed. That is the same distinction the validator's `None`
        verdict makes, one layer down; the row below it (sealed to a key we no
        longer hold) is genuinely unopenable and IS acked.
        """
        import bot.utils.credential_pull as cp
        monkeypatch.delenv("WEB_CREDS_KEY", raising=False)
        payload = json.dumps(_seal({"api_key": "AK", "api_secret": "S",
                                    "passphrase": "P"}, cs.public_key_pem()))
        cs._cache.clear()

        def _boom():
            raise cs.SealingKeyUnavailable("permission denied")

        monkeypatch.setattr(cs, "load_or_create_private_key", _boom)

        class _Store:
            def set(self, *a):
                raise AssertionError("nothing opened, nothing to store")

        acks = cp.process_pending(
            [{"user_id": 1, "telegram_id": "999", "action": "connect",
              "encrypted_payload": payload}], _Store())
        assert acks == [], "an unreadable key must not clear the user's submission"

    def test_a_row_sealed_to_a_key_we_lost_is_acked_failed_not_retried_forever(
            self, statedir, monkeypatch):
        import bot.utils.credential_pull as cp
        monkeypatch.delenv("WEB_CREDS_KEY", raising=False)
        payload = json.dumps(_seal({"api_key": "AK", "api_secret": "S",
                                    "passphrase": "P"}, cs.public_key_pem()))
        cs.private_key_path().unlink()          # a wiped data/ — new key next call
        cs._cache.clear()

        class _Store:
            def set(self, *a):
                raise AssertionError("nothing openable, nothing to store")

        acks = cp.process_pending(
            [{"user_id": 1, "telegram_id": "999", "action": "connect",
              "encrypted_payload": payload}], _Store())
        assert acks[0]["ok"] is False


@pytest.fixture()
def publisher(monkeypatch):
    """The publisher with a paired website and a clean memory.

    The state is reset through `_fresh_publish_state()` rather than a literal
    written here: a test that hand-built the dict would keep passing with a
    field missing until something read it, three releases later.
    """
    import bot.utils.credential_pull as cp
    monkeypatch.setattr(cp, "SYNC_SECRET", "s" * 48)
    monkeypatch.setattr(cp, "_published", cp._fresh_publish_state())
    return cp


class TestPublishing:
    def test_publishes_the_record_and_reports_the_website_took_it(
            self, statedir, publisher, monkeypatch):
        cp = publisher
        seen = []

        def _fake(path, data=None):
            seen.append((path, data))
            return {"ok": True}

        monkeypatch.setattr(cp, "_request", _fake)
        assert cp.publish_sealing_key() is True
        path, data = seen[0]
        assert path.endswith("/credentials/sealing-key")
        assert data == cs.public_key_record()
        assert "PRIVATE" not in data["pem"], "only the public half is ever sent"

    def test_a_website_that_refuses_is_retried_not_recorded_as_done(
            self, statedir, publisher, monkeypatch):
        """Fail-open on the CALL, fail-closed on the RECORD. Marking a refused
        publish as published would leave the form off until the next key
        change — a state nothing would report."""
        cp = publisher
        monkeypatch.setattr(cp, "_request", lambda p, d=None: None)   # site down
        assert cp.publish_sealing_key() is False
        assert cp._published["kid"] is None

    def test_a_refusal_backs_the_RETRY_off_not_the_key_change(
            self, statedir, publisher, monkeypatch):
        """The pull ticks every 30s and the realistic refusal is a website
        still running the build with no such endpoint. Retrying — and warning
        — on every tick is 2,880 identical lines a day, which is how an
        operator learns to scroll past warnings.

        But the backoff is per KEY. A regenerated key after a wiped data/ is
        the case that most needs to reach the website at once: until it does,
        every row queued there is sealed to a key the bot no longer holds.
        """
        cp = publisher
        calls = []
        monkeypatch.setattr(cp, "_request",
                            lambda p, d=None: (calls.append(d["kid"]), None)[1])
        assert cp.publish_sealing_key() is False
        assert cp.publish_sealing_key() is False
        assert len(calls) == 1, "a refusal must not be retried on the very next tick"
        # A NEW key goes out immediately, backoff or not.
        cs.private_key_path().unlink()
        cs._cache.clear()
        assert cp.publish_sealing_key() is False
        assert len(calls) == 2 and calls[0] != calls[1]
        # And the retry does happen once the window passes.
        cp._published["tried"] -= cp.PUBLISH_RETRY_S + 1
        assert cp.publish_sealing_key() is False
        assert len(calls) == 3

    def test_a_key_change_republishes_before_the_hourly_interval(
            self, statedir, publisher, monkeypatch):
        cp = publisher
        calls = []
        monkeypatch.setattr(cp, "_request",
                            lambda p, d=None: (calls.append(d["kid"]), {"ok": True})[1])
        assert cp.publish_sealing_key() is True
        assert cp.publish_sealing_key() is True          # unchanged: no second POST
        assert len(calls) == 1
        cs.private_key_path().unlink()                   # data/ wiped: new key
        cs._cache.clear()
        assert cp.publish_sealing_key() is True
        assert len(calls) == 2 and calls[0] != calls[1]

    def test_publishing_needs_the_sync_channel(self, statedir, monkeypatch):
        import bot.utils.credential_pull as cp
        monkeypatch.setattr(cp, "SYNC_SECRET", "")
        monkeypatch.setattr(cp, "_request", lambda p, d=None: pytest.fail("no channel"))
        assert cp.publish_sealing_key() is False
