#!/usr/bin/env python3
"""Generate docs/lessons/INDEX.md from docs/lessons/ENGINEERING_LOG.md.

The log is the repository's incident history: every chapter that used to live
in CLAUDE.md, moved verbatim on 2026-09-29 so the agent guide could fit in a
context window. It is about 20,000 lines, so it needs an index a person or an
agent can read first. This script builds that index from the log itself:

- each ``##``/``###`` section, with its line;
- each chapter lead (a paragraph opening with a bold ALL-CAPS sentence), with
  its line;
- the guard tests each chapter cites (``tests/...`` and ``app/test/...``
  paths inside it), so a reader can go from a lesson to the test that holds it.

The index is generated, never hand-edited: ``--check`` exits 1 when the
committed index is not what this script produces, and a test runs it.

Usage:
    python3 scripts/lessons_index.py           # rewrite docs/lessons/INDEX.md
    python3 scripts/lessons_index.py --check   # exit 1 if it is stale
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOG = ROOT / "docs" / "lessons" / "ENGINEERING_LOG.md"
INDEX = ROOT / "docs" / "lessons" / "INDEX.md"

_HEADING = re.compile(r"^(#{2,3}) (.+?)\s*$")
_LEAD = re.compile(r"^\*\*([^*]{12,}?)\*\*")
_TEST = re.compile(r"(?<![\w/])((?:tests|app/test)/[\w./-]+\.(?:py|js))")


def _is_lead(text: str) -> bool:
    letters = [c for c in text if c.isalpha()]
    return bool(letters) and sum(c.isupper() for c in letters) / len(letters) > 0.8


def _clean(text: str) -> str:
    text = text.strip().rstrip(".:")
    return text.replace("|", "\\|")


def build(log_text: str) -> str:
    lines = log_text.splitlines()
    entries: list[tuple[int, str, str]] = []   # (line, kind, title)
    for i, line in enumerate(lines, 1):
        m = _HEADING.match(line)
        if m:
            entries.append((i, "section" if m.group(1) == "##" else "subsection",
                            m.group(2)))
            continue
        m = _LEAD.match(line)
        if m and _is_lead(m.group(1)):
            entries.append((i, "chapter", m.group(1)))

    out = [
        "# Lessons index",
        "",
        "Generated by `scripts/lessons_index.py` from",
        "`docs/lessons/ENGINEERING_LOG.md`; do not edit by hand. Each row is a",
        "section or a chapter lead in the log, with the line it starts on and the",
        "guard tests the chapter cites. Search this file for the subsystem you are",
        "about to change before changing it.",
        "",
    ]
    for n, (line, kind, title) in enumerate(entries):
        end = entries[n + 1][0] - 1 if n + 1 < len(entries) else len(lines)
        if kind == "section":
            out += ["", f"## {_clean(title)} (line {line})", ""]
            continue
        if kind == "subsection":
            out += ["", f"### {_clean(title)} (line {line})", ""]
            continue
        span = "\n".join(lines[line - 1:end])
        tests = sorted(set(_TEST.findall(span)))
        cite = f" — {', '.join(f'`{t}`' for t in tests)}" if tests else ""
        out.append(f"- L{line}: {_clean(title)}{cite}")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str]) -> int:
    text = build(LOG.read_text(encoding="utf-8"))
    if "--check" in argv:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != text:
            print("docs/lessons/INDEX.md is stale: run python3 scripts/lessons_index.py")
            return 1
        return 0
    INDEX.write_text(text, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
