#!/usr/bin/env python3
"""Render the one vocabulary of secret shapes for the website to read.

`bot/utils/secret_shapes.py` is the source: eight rows, each with the example
it must scrub and the decoy it must leave alone. `app/lib/safe_error.js` is a
SECOND RUNTIME that needs the same rows — its own header calls itself "the same
rule the bot enforces with `_safe_exc_text`" — and it had a second vocabulary
instead, wider on labels and narrower on token shapes, which is how it came to
print a Telegram bot token, a bare provider key, a JWT and the three env names
whose values decrypt everything else on the box.

A second author reading the first author's table is the shape this repository
spends its guard tests preventing, so the rows TRAVEL: this renders them into
`app/lib/secret_shapes.generated.json`, that file is committed, and
`tests/test_the_website_reads_this_vocabulary.py` renders it again and compares
byte for byte — the README command tables' rule, for the same reason. Run it
after any change to `SHAPES`:

    python3 scripts/render_secret_shapes.py           # write the artifact
    python3 scripts/render_secret_shapes.py --check   # exit 1 if it is stale

Patterns are emitted verbatim. Every row in this table is written in the subset
both engines read the same way (character classes, `\\b`, `(?:…)`, bounded
repeats); a row that needs a Python-only construct — a named group, a lookbehind
— cannot be rendered honestly and the JS test that drives every row's example
would be the thing that says so.
"""
from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from bot.utils.secret_shapes import REDACTED, table_rows  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "app" / "lib" / "secret_shapes.generated.json"


def rendered() -> str:
    doc = {
        "//": (
            "GENERATED by scripts/render_secret_shapes.py from bot/utils/secret_shapes.py — "
            "do not edit. tests/test_the_website_reads_this_vocabulary.py fails if it is stale."
        ),
        "redacted": REDACTED,
        "rows": table_rows(),
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str]) -> int:
    text = rendered()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current == text:
            print(f"{OUT.name} is current ({len(table_rows())} rows).")
            return 0
        print(f"{OUT.name} is STALE — run: python3 scripts/render_secret_shapes.py", file=sys.stderr)
        return 1
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(table_rows())} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
