/**
 * Sealed credential submissions — the path that replaced the key ceremony.
 *
 * WHAT BROKE. Submitting exchange API keys on the website required
 * WEB_CREDS_KEY: 32 random bytes an operator generated by hand and set
 * IDENTICALLY in the bot's environment and this app's. Until both were set the
 * form answered 503, and the report that started this was, in effect, "I typed
 * my keys in and nothing saved". It also handed the website a key it had no
 * business holding — this app could read back every submission it stored.
 *
 * WHAT REPLACED IT. The bot generates a keypair on first use and publishes the
 * public half over the sync channel it already authenticates on. Each
 * submission is sealed to it: a fresh AES-256-GCM content key, wrapped with
 * RSA-OAEP(SHA-256). Nothing is configured by hand and the site cannot reopen
 * what it stores.
 *
 * These pin both halves of that claim and the refusal that guards it — a
 * submission is NEVER queued unprotected, and the 503 says which of the two
 * paths is missing rather than leaving a user to wonder what they mistyped.
 *
 * Deliberately NO WEB_CREDS_KEY in this process: the sealed path must work
 * with nothing else configured, which is the entire point.
 *
 * Run: npm test  (node --test test/)
 */

process.env.JWT_SECRET = 'j'.repeat(64);
process.env.BOT_SYNC_SECRET = 's'.repeat(48);
delete process.env.WEB_CREDS_KEY;

const test = require('node:test');
const assert = require('node:assert');
const crypto = require('node:crypto');
const http = require('node:http');
const jwt = require('jsonwebtoken');

const { pool } = require('../db');
const creds = require('../lib/creds_crypto');

let server, base, token, uid;

function rsa(bits) {
  return crypto.generateKeyPairSync('rsa', { modulusLength: bits });
}

function pemOf(pair) {
  return pair.publicKey.export({ type: 'spki', format: 'pem' }).toString();
}

/** Open a v2 envelope the way the bot does — the only proof that matters. */
function unseal(envelope, privateKey) {
  const e = JSON.parse(envelope);
  const contentKey = crypto.privateDecrypt(
    { key: privateKey, padding: crypto.constants.RSA_PKCS1_OAEP_PADDING, oaepHash: 'sha256' },
    Buffer.from(e.ek, 'base64'));
  const d = crypto.createDecipheriv('aes-256-gcm', contentKey, Buffer.from(e.iv, 'base64'));
  d.setAuthTag(Buffer.from(e.tag, 'base64'));
  const pt = Buffer.concat([d.update(Buffer.from(e.ct, 'base64')), d.final()]);
  return JSON.parse(pt.toString('utf8'));
}

function request(method, path, { token, secret, body } = {}) {
  return new Promise((resolve, reject) => {
    const payload = body ? JSON.stringify(body) : null;
    const r = http.request(`${base}${path}`, {
      method,
      headers: {
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
        ...(secret ? { 'x-bot-secret': secret } : {}),
        ...(payload ? { 'Content-Type': 'application/json' } : {}),
      },
    }, (res) => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => resolve({ status: res.statusCode, data: d ? JSON.parse(d) : {} }));
    });
    r.on('error', reject);
    if (payload) r.write(payload);
    r.end();
  });
}

// One keypair for the whole file — RSA keygen is the slow part, not the seal.
const BOT = rsa(3072);
const BOT_PEM = pemOf(BOT);

test.before(async () => {
  await pool.execute('INSERT INTO users (email, password_hash, name) VALUES (?, ?, ?)',
    ['seal@test.io', 'x', 'S']);
  const [rows] = await pool.execute('SELECT id FROM users WHERE email = ?', ['seal@test.io']);
  uid = rows[0].id;
  await pool.execute('UPDATE users SET telegram_id = ? WHERE id = ?', ['7007', uid]);
  const [u] = await pool.execute('SELECT * FROM users WHERE id = ?', [uid]);
  u[0].telegram_linked = true;   // MemoryDB: set the flag directly
  token = jwt.sign({ user_id: uid, email: 'seal@test.io' }, process.env.JWT_SECRET);

  const express = require('express');
  const app = express();
  app.use(express.json());
  app.use('/api/credentials', require('../routes/credentials'));
  app.use('/api/bot/sync', require('../routes/sync'));
  await new Promise((res) => { server = app.listen(0, '127.0.0.1', res); });
  base = `http://127.0.0.1:${server.address().port}`;
});

test.after(() => { if (server) server.close(); });

// ── the fingerprint both runtimes compute ──────────────────────────────────

test('kidFor hashes the KEY, not the text that carries it', () => {
  const kid = creds.kidFor(BOT_PEM);
  assert.match(kid, /^[0-9a-f]{16}$/);
  // PEM is not canonical: line width and trailing whitespace are formatting,
  // and a fingerprint that moved with them would disagree with the bot for a
  // reason that has nothing to do with the key.
  const rewrapped = BOT_PEM.replace(/\n/g, '\r\n') + '\n\n';
  assert.strictEqual(creds.kidFor(rewrapped), kid);
  // And it is a fingerprint OF this key: another key is another kid.
  assert.notStrictEqual(creds.kidFor(pemOf(rsa(2048))), kid);
});

// ── the seal ───────────────────────────────────────────────────────────────

test('sealJSON produces a v2 envelope only the private key opens', () => {
  const env = JSON.parse(creds.sealJSON({ venue: 'bybit', api_key: 'AK' }, { pem: BOT_PEM }));
  assert.strictEqual(env.v, 2);
  assert.strictEqual(env.alg, creds.SEAL_ALG);
  assert.strictEqual(env.kid, creds.kidFor(BOT_PEM));
  // 12-byte IV and a 16-byte tag split out of the ciphertext — the same
  // convention the v1 envelope uses, because Python re-joins them.
  assert.strictEqual(Buffer.from(env.iv, 'base64').length, 12);
  assert.strictEqual(Buffer.from(env.tag, 'base64').length, 16);
  assert.strictEqual(unseal(JSON.stringify(env), BOT.privateKey).api_key, 'AK');
});

test('the plaintext is nowhere in the envelope', () => {
  const env = creds.sealJSON({ api_key: 'SECRET_AK_VALUE', api_secret: 'SECRET_SEC' },
    { pem: BOT_PEM });
  assert.ok(!env.includes('SECRET_AK_VALUE'));
  assert.ok(!env.includes('SECRET_SEC'));
});

test('a fresh content key per submission — two seals of the same object differ', () => {
  const a = JSON.parse(creds.sealJSON({ api_key: 'AK' }, { pem: BOT_PEM }));
  const b = JSON.parse(creds.sealJSON({ api_key: 'AK' }, { pem: BOT_PEM }));
  assert.notStrictEqual(a.ct, b.ct);
  assert.notStrictEqual(a.ek, b.ek);
  assert.strictEqual(a.kid, b.kid);
});

test('a tampered envelope does not open — it fails', () => {
  const e = JSON.parse(creds.sealJSON({ api_key: 'AK' }, { pem: BOT_PEM }));
  const ct = Buffer.from(e.ct, 'base64');
  ct[0] ^= 0xff;
  e.ct = ct.toString('base64');
  assert.throws(() => unseal(JSON.stringify(e), BOT.privateKey));
});

test('sealing refuses a key it cannot vouch for', () => {
  // Not RSA.
  const ed = crypto.generateKeyPairSync('ed25519');
  assert.throws(() => creds.sealJSON({ a: 1 },
    { pem: ed.publicKey.export({ type: 'spki', format: 'pem' }).toString() }), /RSA/);
  // RSA, but small enough that the seal would be decoration.
  assert.throws(() => creds.sealJSON({ a: 1 }, { pem: pemOf(rsa(1024)) }), /minimum/);
  // Not a key at all.
  assert.throws(() => creds.sealJSON({ a: 1 }, { pem: 'not a pem' }));
});

test('a record whose kid disagrees with its key is refused, not stamped', () => {
  // Sealing to the PEM and stamping the CLAIMED kid would produce an envelope
  // the bot rejects — discovered at submit time, on the user's screen.
  assert.throws(
    () => creds.sealJSON({ a: 1 }, { pem: BOT_PEM, kid: '0'.repeat(16) }),
    /disagrees/);
});

// ── publishing, and what it turns on ───────────────────────────────────────

test('with nothing published the form refuses, and says which half is missing', async () => {
  const s = await request('GET', '/api/credentials/status', { token });
  assert.strictEqual(s.data.crypto_ready, false);
  assert.strictEqual(s.data.crypto_mode, 'off');
  assert.strictEqual(s.data.crypto_reason, 'awaiting_bot_key');

  const r = await request('POST', '/api/credentials', {
    token, body: { venue: 'bybit', api_key: 'k'.repeat(16), api_secret: 's'.repeat(16) },
  });
  assert.strictEqual(r.status, 503);
  assert.strictEqual(r.data.reason, 'awaiting_bot_key');
  assert.ok(/try again/i.test(r.data.detail), 'the refusal must tell the user what to do');
  // NOTHING was queued. A row here would be keys nobody can open.
  const [pend] = await pool.execute(
    'SELECT user_id FROM pending_credentials WHERE user_id = ?', [uid]);
  assert.strictEqual(pend.length, 0);
});

test('the publish endpoint needs the bot secret', async () => {
  const r = await request('POST', '/api/bot/sync/credentials/sealing-key', {
    body: { kid: creds.kidFor(BOT_PEM), pem: BOT_PEM, alg: creds.SEAL_ALG },
  });
  assert.strictEqual(r.status, 403);
});

test('an unusable published key is rejected 400, not stored to fail later', async () => {
  for (const body of [
    { pem: pemOf(rsa(1024)), alg: creds.SEAL_ALG },              // undersized
    { pem: BOT_PEM, alg: 'rot13' },                              // wrong algorithm
    { pem: BOT_PEM, alg: creds.SEAL_ALG, kid: 'f'.repeat(16) },  // self-inconsistent
    { pem: 'nope', alg: creds.SEAL_ALG },                        // not a key
  ]) {
    const r = await request('POST', '/api/bot/sync/credentials/sealing-key',
      { secret: process.env.BOT_SYNC_SECRET, body });
    assert.strictEqual(r.status, 400, JSON.stringify(body.alg || body.pem.slice(0, 20)));
    assert.strictEqual(r.data.error, 'unusable_sealing_key');
  }
  // Still off — a rejected record must not have been written.
  const s = await request('GET', '/api/credentials/status', { token });
  assert.strictEqual(s.data.crypto_reason, 'awaiting_bot_key');
});

test('publishing the key turns the form on with nothing else configured', async () => {
  assert.strictEqual(creds.isConfigured(), false, 'no shared key in this process');
  const p = await request('POST', '/api/bot/sync/credentials/sealing-key', {
    secret: process.env.BOT_SYNC_SECRET,
    body: { kid: creds.kidFor(BOT_PEM), pem: BOT_PEM, alg: creds.SEAL_ALG },
  });
  assert.strictEqual(p.status, 200);
  assert.strictEqual(p.data.kid, creds.kidFor(BOT_PEM));

  const s = await request('GET', '/api/credentials/status', { token });
  assert.strictEqual(s.data.crypto_ready, true);
  assert.strictEqual(s.data.crypto_mode, 'sealed');
  assert.strictEqual(s.data.crypto_reason, null);
});

test('a submission is sealed to the bot, and this app cannot read it back', async () => {
  const r = await request('POST', '/api/credentials', {
    token,
    body: { venue: 'bybit', api_key: 'BYKEY' + 'k'.repeat(12), api_secret: 'BYSEC' + 's'.repeat(12) },
  });
  assert.strictEqual(r.status, 200);
  const [pend] = await pool.execute(
    'SELECT exchange, encrypted_payload FROM pending_credentials WHERE user_id = ?', [uid]);
  assert.strictEqual(pend[0].exchange, 'bybit');
  const stored = pend[0].encrypted_payload;

  // The bot opens it.
  const opened = unseal(stored, BOT.privateKey);
  assert.strictEqual(opened.venue, 'bybit');
  assert.strictEqual(opened.api_key, 'BYKEY' + 'k'.repeat(12));

  // The website cannot. This is the property the whole change buys, so it is
  // asserted against the SHIPPED reader rather than by reading the source: the
  // legacy path is not merely unused here, it is unusable.
  //
  // WITH A SHARED KEY SET, deliberately. This process has none, so a bare
  // `assert.throws(decryptJSON)` would pass on "WEB_CREDS_KEY missing" — an
  // assertion satisfied by the absence of the thing it is supposed to be
  // proving useless. Set one, and the throw is the AEAD refusing to
  // authenticate a payload sealed to somebody else's key.
  assert.strictEqual(JSON.parse(stored).v, 2);
  process.env.WEB_CREDS_KEY = Buffer.alloc(32, 3).toString('base64');
  try {
    assert.strictEqual(creds.isConfigured(), true, 'the legacy reader is armed for this check');
    assert.throws(() => creds.decryptJSON(stored));
  } finally {
    delete process.env.WEB_CREDS_KEY;
  }
  assert.ok(!stored.includes('BYKEY'));
});

test('the pull hands the bot exactly what was stored', async () => {
  const r = await request('GET', '/api/bot/sync/credentials/pending',
    { secret: process.env.BOT_SYNC_SECRET });
  const row = (r.data.pending || []).find(p => String(p.user_id) === String(uid));
  assert.ok(row, 'the sealed row must reach the bot');
  assert.strictEqual(unseal(row.encrypted_payload, BOT.privateKey).api_secret,
    'BYSEC' + 's'.repeat(12));
});

test('a republished key replaces the old one and later seals use it', async () => {
  const NEXT = rsa(2048);
  const nextPem = pemOf(NEXT);
  const p = await request('POST', '/api/bot/sync/credentials/sealing-key', {
    secret: process.env.BOT_SYNC_SECRET,
    body: { kid: creds.kidFor(nextPem), pem: nextPem, alg: creds.SEAL_ALG },
  });
  assert.strictEqual(p.status, 200);
  const r = await request('POST', '/api/credentials', {
    token, body: { venue: 'bybit', api_key: 'n'.repeat(16), api_secret: 'm'.repeat(16) },
  });
  assert.strictEqual(r.status, 200);
  const [pend] = await pool.execute(
    'SELECT encrypted_payload FROM pending_credentials WHERE user_id = ?', [uid]);
  assert.strictEqual(JSON.parse(pend[0].encrypted_payload).kid, creds.kidFor(nextPem));
  assert.strictEqual(unseal(pend[0].encrypted_payload, NEXT.privateKey).api_key, 'n'.repeat(16));
});

test('a STORED key that no longer vets is its own reason, not "never published"',
  async () => {
    // A record can stop being usable after it was accepted — this build drops
    // an algorithm, a row is rewritten. Reporting that as `awaiting_bot_key`
    // would tell an operator to wait for a publish that already happened.
    const [prev] = await pool.execute(
      'SELECT kid, pem, alg FROM bot_sealing_key WHERE id = 1');
    await pool.execute(
      'REPLACE INTO bot_sealing_key (id, kid, pem, alg) VALUES (1, ?, ?, ?)',
      [prev[0].kid, prev[0].pem, 'rot13']);
    try {
      const s = await request('GET', '/api/credentials/status', { token });
      assert.strictEqual(s.data.crypto_ready, false);   // we DO know it is off
      assert.strictEqual(s.data.crypto_reason, 'sealing_key_unusable');
      const r = await request('POST', '/api/credentials', {
        token, body: { venue: 'bybit', api_key: 'k'.repeat(16), api_secret: 's'.repeat(16) },
      });
      assert.strictEqual(r.status, 503);
      assert.strictEqual(r.data.reason, 'sealing_key_unusable');
      assert.ok(/operator/i.test(r.data.detail), 'retrying will not help — say so');
    } finally {
      await pool.execute(
        'REPLACE INTO bot_sealing_key (id, kid, pem, alg) VALUES (1, ?, ?, ?)',
        [prev[0].kid, prev[0].pem, prev[0].alg]);
    }
  });

// ── unreadable is not absent ───────────────────────────────────────────────

test('a key store that cannot be read refuses WITHOUT claiming the bot never called',
  async (t) => {
    const real = pool.execute.bind(pool);
    t.mock.method(pool, 'execute', async (sql, params) => {
      if (String(sql).includes('bot_sealing_key')) throw new Error('connection lost');
      return real(sql, params);
    });
    const s = await request('GET', '/api/credentials/status', { token });
    // NOT false: false is the claim "this form is off", and a read that failed
    // has not earned it.
    assert.strictEqual(s.data.crypto_ready, null);
    assert.strictEqual(s.data.crypto_reason, 'sealing_key_unreadable');

    const r = await request('POST', '/api/credentials', {
      token, body: { venue: 'bybit', api_key: 'k'.repeat(16), api_secret: 's'.repeat(16) },
    });
    assert.strictEqual(r.status, 503);
    assert.strictEqual(r.data.reason, 'sealing_key_unreadable');
    assert.ok(!/has not published/i.test(r.data.detail || ''),
      'a database fault must not be reported as a bot that never called');
  });
