'use strict';
/**
 * Node-side secrets-vault reader — the website's half of the wiped-.env
 * self-heal. These tests prove the Express app can decrypt the SAME encrypted
 * vault the Python bot writes, using a fixture generated by Python's
 * cryptography.Fernet (not a Node round-trip) — so real cross-language
 * compatibility is asserted, not just internal consistency.
 *
 * It also proves the safety spine: a live env value is never overridden, and a
 * missing/bad key or tampered token restores NOTHING and never throws.
 */

const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');

const { restoreFromVault, fernetDecrypt } = require('../lib/secrets_vault');

// ── Real Python-Fernet fixture ─────────────────────────────────────────────
// Generated with cryptography.Fernet: key + a vault holding two web secrets.
const MASTER_KEY = '591JzztgVfgBBMP8CQR-kWg410Osnn8DPNLKJ3jOCKU=';
const VAULT = {
  BOT_SYNC_SECRET: 'gAAAAABqYOra2xIqsigJQxQgy8Z7GSk-LSlBY1vt_U-0I6nkn0_yhIgIyAdrW8j17mLWoq3miKUYX4oPwFT7lzU_aHAhgbg49zDoICW9kMx3NytLsb7JM2DiygLkTBDTOB-8FBlUCkFZ',
  WEB_GATEWAY_SECRET: 'gAAAAABqYOra-Bzc3QWjfc9GOgd1XcYjhz_jalxYSlEFP1SFRfMNk6N2dLWtUo094vPP_KDgLcyeXYYiKJJpBp4IYcGIxNW4ITwbxRHt1_9xaTT_1F2F4M97ZioO1ALatGNCARrCBZcc',
};
const EXPECT = {
  BOT_SYNC_SECRET: 'sync-secret-of-at-least-32-characters-long-xyz',
  WEB_GATEWAY_SECRET: 'gateway-secret-also-32-plus-chars-longggg',
};

function writeVault(dir, { key = MASTER_KEY, vault = VAULT } = {}) {
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, '.exchange_secret.key'), key);
  fs.writeFileSync(path.join(dir, 'secrets_vault.enc'), JSON.stringify(vault));
}

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'rc-vault-'));
}

test('decrypts a real Python-Fernet vault and restores missing web secrets', () => {
  const dir = tmpDir();
  writeVault(dir);
  const env = {}; // empty environment — simulates a wiped .env
  const restored = restoreFromVault({ env, dirs: [dir], keys: Object.keys(VAULT) });
  assert.deepStrictEqual(restored.sort(), ['BOT_SYNC_SECRET', 'WEB_GATEWAY_SECRET']);
  assert.strictEqual(env.BOT_SYNC_SECRET, EXPECT.BOT_SYNC_SECRET);
  assert.strictEqual(env.WEB_GATEWAY_SECRET, EXPECT.WEB_GATEWAY_SECRET);
});

test('a live env value is never overridden by the vault', () => {
  const dir = tmpDir();
  writeVault(dir);
  const env = { BOT_SYNC_SECRET: 'the-live-one-from-a-healthy-env-32chars' };
  const restored = restoreFromVault({ env, dirs: [dir], keys: Object.keys(VAULT) });
  // Only the genuinely-missing key is restored; the live one is untouched.
  assert.deepStrictEqual(restored, ['WEB_GATEWAY_SECRET']);
  assert.strictEqual(env.BOT_SYNC_SECRET, 'the-live-one-from-a-healthy-env-32chars');
});

test('nothing to heal when every key is already present (the common case)', () => {
  const dir = tmpDir();
  writeVault(dir);
  const env = { BOT_SYNC_SECRET: 'x'.repeat(40), WEB_GATEWAY_SECRET: 'y'.repeat(40) };
  const restored = restoreFromVault({ env, dirs: [dir], keys: Object.keys(VAULT) });
  assert.deepStrictEqual(restored, []);
});

test('fail-open: a wrong master key restores nothing and does not throw', () => {
  const dir = tmpDir();
  // A valid-shape but WRONG Fernet key.
  writeVault(dir, { key: Buffer.alloc(32, 7).toString('base64') });
  const env = {};
  const restored = restoreFromVault({ env, dirs: [dir], keys: Object.keys(VAULT) });
  assert.deepStrictEqual(restored, []);
  assert.strictEqual(env.BOT_SYNC_SECRET, undefined);
});

test('fail-open: a tampered token fails the HMAC and is skipped', () => {
  const dir = tmpDir();
  const tampered = { ...VAULT, BOT_SYNC_SECRET: VAULT.BOT_SYNC_SECRET.slice(0, -4) + 'AAAA' };
  writeVault(dir, { vault: tampered });
  const env = {};
  const restored = restoreFromVault({ env, dirs: [dir], keys: Object.keys(VAULT) });
  // The tampered one is dropped; the intact one still restores.
  assert.deepStrictEqual(restored, ['WEB_GATEWAY_SECRET']);
  assert.strictEqual(env.BOT_SYNC_SECRET, undefined);
});

test('fail-open: absent vault directory restores nothing and does not throw', () => {
  const env = {};
  const restored = restoreFromVault({
    env, dirs: [path.join(os.tmpdir(), 'rc-does-not-exist-xyz')], keys: Object.keys(VAULT),
  });
  assert.deepStrictEqual(restored, []);
});

test('fernetDecrypt returns null on garbage input rather than throwing', () => {
  const rawKey = Buffer.from(MASTER_KEY, 'base64');
  assert.strictEqual(fernetDecrypt(rawKey, 'not-a-real-token'), null);
  assert.strictEqual(fernetDecrypt(rawKey, ''), null);
});

test('server.js wires the vault restore before the BOT_SYNC_SECRET fatal check', () => {
  const server = fs.readFileSync(path.join(__dirname, '..', 'server.js'), 'utf8');
  const restoreAt = server.indexOf("require('./lib/secrets_vault')");
  const fatalAt = server.indexOf('FATAL: BOT_SYNC_SECRET');
  assert.ok(restoreAt > -1, 'server.js requires the vault reader');
  assert.ok(fatalAt > -1, 'server.js has the BOT_SYNC_SECRET fatal check');
  assert.ok(restoreAt < fatalAt, 'the vault restore must run BEFORE the fatal check');
});
