'use strict';
/**
 * MH5 — "verify anyone" paste-a-statement verifier.
 *
 * The load-bearing claim: the JS canonicalizer reproduces the Python
 * sealer's bytes exactly. Pinned against a fixture generated with CPython:
 *   json.dumps(bundle, sort_keys=True, separators=(",",":"), ensure_ascii=False)
 * including a non-ASCII key (β), non-ASCII text (ensure_ascii=False keeps it
 * raw), embedded quotes, null/true, and string-numbers (the CSF invariant:
 * the sealer never hashes floats).
 */
process.env.JWT_SECRET = 'j'.repeat(64);

const test = require('node:test');
const assert = require('node:assert');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const { canonicalStringify } = require('../lib/canonical');

// Generated by: python3 -c "import json,hashlib; ..." (see docstring).
const FIXTURE = {
  bundle: { z: '1.50', a: { 'β': 'x', b: ['2', null, true] },
    list: [{ k: 'v' }], note: 'línea…"q"' },
  canonical: '{"a":{"b":["2",null,true],"β":"x"},"list":[{"k":"v"}],"note":"línea…\\"q\\"","z":"1.50"}',
  sha256: 'a327937870bd388f1a97062b222b84dad818dc0a1c274ddab643ecb2c46e7452',
};

test('JS canonicalization matches CPython json.dumps byte-for-byte', () => {
  const c = canonicalStringify(FIXTURE.bundle);
  assert.equal(c, FIXTURE.canonical);
  const h = crypto.createHash('sha256').update(Buffer.from(c, 'utf8')).digest('hex');
  assert.equal(h, FIXTURE.sha256);
});

test('key order is deterministic regardless of insertion order', () => {
  const shuffled = { note: 'línea…"q"', list: [{ k: 'v' }],
    a: { b: ['2', null, true], 'β': 'x' }, z: '1.50' };
  assert.equal(canonicalStringify(shuffled), FIXTURE.canonical);
});

test('a single mutated character changes the hash — tampering is visible', () => {
  const tampered = JSON.parse(JSON.stringify(FIXTURE.bundle));
  tampered.z = '1.51';
  const h = crypto.createHash('sha256')
    .update(Buffer.from(canonicalStringify(tampered), 'utf8')).digest('hex');
  assert.notEqual(h, FIXTURE.sha256);
});

test('the /proof page carries the paste-verifier, offline and equivalent', () => {
  const html = fs.readFileSync(
    path.join(__dirname, '..', 'public', 'proof.html'), 'utf8');
  assert.match(html, /Verify anyone — paste a statement/);
  assert.match(html, /entirely in your\s+browser/, 'offline promise on the page');
  assert.match(html, /MISMATCH — the pasted statement does NOT hash/);
  // The page's inline canonicalizer must stay the same algorithm as the lib:
  // recursive key sort over JSON.stringify — pin its two load-bearing lines.
  assert.ok(html.includes("Object.keys(obj).sort().map(k =>"),
    'inline canonical() keeps the recursive key sort');
  assert.ok(html.includes("if (Array.isArray(obj)) return '[' + obj.map(canonical).join(',') + ']'"),
    'inline canonical() keeps array handling');
  // Fully offline: the handler never fetches.
  const handler = html.slice(html.indexOf("vaBtn.addEventListener"));
  assert.ok(!handler.includes('fetch('), 'paste verification never leaves the device');
});
