'use strict';
/**
 * MH5 — "verify anyone" paste-a-statement verifier.
 *
 * The load-bearing claim: the JS canonicalizer reproduces the Python
 * sealer's bytes exactly. Pinned against a fixture generated with CPython:
 *   json.dumps(bundle, sort_keys=True, separators=(",",":"), ensure_ascii=False)
 * including a non-ASCII key (β), non-ASCII text (ensure_ascii=False keeps it
 * raw), embedded quotes, null/true, and string-numbers (the CSF invariant:
 * the sealer never hashes floats).
 */
process.env.JWT_SECRET = 'j'.repeat(64);

const test = require('node:test');
const assert = require('node:assert');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const { canonicalStringify } = require('../lib/canonical');

// Generated by: python3 -c "import json,hashlib; ..." (see docstring).
const FIXTURE = {
  bundle: { z: '1.50', a: { 'β': 'x', b: ['2', null, true] },
    list: [{ k: 'v' }], note: 'línea…"q"' },
  canonical: '{"a":{"b":["2",null,true],"β":"x"},"list":[{"k":"v"}],"note":"línea…\\"q\\"","z":"1.50"}',
  sha256: 'a327937870bd388f1a97062b222b84dad818dc0a1c274ddab643ecb2c46e7452',
};

test('JS canonicalization matches CPython json.dumps byte-for-byte', () => {
  const c = canonicalStringify(FIXTURE.bundle);
  assert.equal(c, FIXTURE.canonical);
  const h = crypto.createHash('sha256').update(Buffer.from(c, 'utf8')).digest('hex');
  assert.equal(h, FIXTURE.sha256);
});

test('key order is deterministic regardless of insertion order', () => {
  const shuffled = { note: 'línea…"q"', list: [{ k: 'v' }],
    a: { b: ['2', null, true], 'β': 'x' }, z: '1.50' };
  assert.equal(canonicalStringify(shuffled), FIXTURE.canonical);
});

test('a single mutated character changes the hash — tampering is visible', () => {
  const tampered = JSON.parse(JSON.stringify(FIXTURE.bundle));
  tampered.z = '1.51';
  const h = crypto.createHash('sha256')
    .update(Buffer.from(canonicalStringify(tampered), 'utf8')).digest('hex');
  assert.notEqual(h, FIXTURE.sha256);
});

test('the /proof page carries the paste-verifier, offline and equivalent', () => {
  const html = fs.readFileSync(
    path.join(__dirname, '..', 'public', 'proof.html'), 'utf8');
  assert.match(html, /Verify anyone — paste a statement/);
  assert.match(html, /entirely in your\s+browser/, 'offline promise on the page');
  assert.match(html, /MISMATCH — the pasted statement does NOT hash/);
  // THE AGREEMENT CHECK USED TO LIVE HERE, AND IT WAS TWO STRING MATCHES:
  //
  //   assert.ok(html.includes("Object.keys(obj).sort().map(k =>"))
  //   assert.ok(html.includes("if (Array.isArray(obj)) return '[' + ..."))
  //
  // The comment above them said the inline canonicalizer "must stay the same
  // algorithm as the lib". What the assertions actually checked was that two
  // particular lines of text were present — and the two implementations HAD
  // already diverged, in a line neither pattern mentions: the library filters
  // `undefined` values and refuses non-finite numbers, and the page did
  // neither, so `{a:'1', b:undefined}` serialised here as
  // `{"a":"1","b":undefined}` — not even valid JSON, and a different hash.
  //
  // A source match cannot see a difference that lives outside the line it
  // matches. `proof_canonical_agreement.test.js` runs BOTH implementations
  // over the CPython fixture and over the shapes that diverged, which is the
  // property this comment was describing all along.
  assert.ok(html.includes('function canonical(obj)'),
    'the inline canonicalizer is gone; proof_canonical_agreement.test.js '
    + 'extracts it by that name');
  // Fully offline: the handler never fetches.
  const handler = html.slice(html.indexOf("vaBtn.addEventListener"));
  assert.ok(!handler.includes('fetch('), 'paste verification never leaves the device');
});
