#!/usr/bin/env node
'use strict';
/**
 * Split the i18n dictionary per language, so a page loads the runtime plus
 * ONE language instead of all fourteen.
 *
 * `public/js/i18n.js` is the source of truth: every key, every language, the
 * runtime, and the module the Node tests require. Every page used to load it
 * whole — 1.9 MB of JavaScript, most of it strings the visitor would never
 * read, on every navigation, before the first paint. A Spanish reader paid
 * for Japanese; an English reader paid for all thirteen others and needed
 * none of them, because the English text is already in the markup.
 *
 * This writes:
 *   public/js/i18n-core.js    the runtime + the ENGLISH strings (the fallback),
 *                             with SPLIT=true and the chunk version map
 *   public/js/i18n/<lang>.js  one list of [key, text] pairs per non-English
 *                             language, folded into a dictionary on load
 *
 * PAIRS, NOT AN OBJECT LITERAL. The first build wrote `"key": "text"` lines,
 * and the secret scanner in CI (gitleaks, generic-api-key) read three of them
 * as credential assignments: a line whose neighbour mentions an authenticator
 * app, followed by `"a11y.tfa_disable": "…"`, is the shape `auth… : value`
 * the rule keys on. A `["key", "text"]` pair has no `:` between name and value
 * and no `:` after the value, so the shape does not occur — and no scanner
 * allowlist has to widen to cover a generated directory.
 *
 * The core is the SOURCE with two well-delimited replacements — the STRINGS
 * literal and the `SPLIT`/`CHUNKS` lines — so the runtime the browser runs is
 * the runtime the tests boot, and `test/i18n_split.test.js` rebuilds from the
 * source and fails unless the committed output is identical: the "committed
 * site is the built site" rule the marketing site already runs under.
 *
 *   node app/scripts/build_i18n.js          # write the outputs
 *   node app/scripts/build_i18n.js --check  # exit 1 if they would change
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const PUB = path.join(__dirname, '..', 'public');
const SRC = path.join(PUB, 'js', 'i18n.js');
const CORE = path.join(PUB, 'js', 'i18n-core.js');
const CHUNK_DIR = path.join(PUB, 'js', 'i18n');

const STRINGS_OPEN = '  var STRINGS = {';
const STRINGS_CLOSE = '  };';
const SPLIT_LINE = '  var SPLIT = false;';
const CHUNKS_LINE = '  var CHUNKS = {};';
const BANNER = '// GENERATED by app/scripts/build_i18n.js from public/js/i18n.js — edit the source, not this file.';

function sha8(text) {
  return crypto.createHash('sha256').update(text).digest('hex').slice(0, 8);
}

/** { core, chunks: {lang: text}, versions: {lang: sha8} } — pure, from the source on disk. */
function build() {
  const src = fs.readFileSync(SRC, 'utf8');
  const lines = src.split('\n');
  const open = lines.indexOf(STRINGS_OPEN);
  if (open < 0) throw new Error(`${STRINGS_OPEN.trim()} not found in i18n.js`);
  const close = lines.indexOf(STRINGS_CLOSE, open + 1);
  if (close < 0) throw new Error('the STRINGS literal never closes');
  const splitAt = lines.indexOf(SPLIT_LINE);
  const chunksAt = lines.indexOf(CHUNKS_LINE);
  if (splitAt < 0 || chunksAt !== splitAt + 1) {
    throw new Error('the SPLIT / CHUNKS lines are not where build_i18n.js expects them');
  }

  delete require.cache[require.resolve(SRC)];
  const api = require(SRC);
  const langs = api.LANGS.map((l) => l.code).filter((c) => c !== 'en');

  const enLines = [];
  const chunks = {};
  for (const code of langs) chunks[code] = [];
  for (const [key, entry] of Object.entries(api.STRINGS)) {
    enLines.push(`    ${JSON.stringify(key)}: { en: ${JSON.stringify(entry.en)} }`);
    for (const code of langs) {
      if (entry[code] != null) chunks[code].push(`  [${JSON.stringify(key)}, ${JSON.stringify(entry[code])}]`);
    }
  }
  const chunkText = {};
  const versions = {};
  for (const code of langs) {
    chunkText[code] = `${BANNER}\n`
      + `(window.RCI18N_DICTS = window.RCI18N_DICTS || {})[${JSON.stringify(code)}] = Object.fromEntries([\n`
      + `${chunks[code].join(',\n')}\n]);\n`;
    versions[code] = sha8(chunkText[code]);
  }
  const core = [
    BANNER,
    '// English strings only; every other language is a chunk under /js/i18n/, loaded on demand.',
    ...lines.slice(0, open),
    STRINGS_OPEN,
    ...enLines.map((l, i) => l + (i < enLines.length - 1 ? ',' : '')),
    STRINGS_CLOSE,
    ...lines.slice(close + 1, splitAt),
    '  var SPLIT = true;',
    `  var CHUNKS = ${JSON.stringify(versions)};`,
    ...lines.slice(chunksAt + 1),
  ].join('\n');
  return { core, chunks: chunkText, versions, langs };
}

/** The files this build would write, as {relative path: text}. */
function outputs() {
  const b = build();
  const out = { 'js/i18n-core.js': b.core };
  for (const code of b.langs) out[`js/i18n/${code}.js`] = b.chunks[code];
  return out;
}

function main(argv) {
  const check = argv.includes('--check');
  const out = outputs();
  let drift = 0;
  for (const [rel, text] of Object.entries(out)) {
    const file = path.join(PUB, rel);
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (cur === text) continue;
    drift += 1;
    if (check) { console.log(`would change: public/${rel}`); continue; }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, text);
    console.log(`wrote public/${rel} (${text.length} bytes)`);
  }
  // A language removed from LANGS leaves a chunk nothing loads; delete it.
  if (fs.existsSync(CHUNK_DIR)) {
    for (const f of fs.readdirSync(CHUNK_DIR)) {
      if (f.endsWith('.js') && !(`js/i18n/${f}` in out)) {
        drift += 1;
        if (check) console.log(`would delete: public/js/i18n/${f}`);
        else { fs.unlinkSync(path.join(CHUNK_DIR, f)); console.log(`deleted public/js/i18n/${f}`); }
      }
    }
  }
  if (check) {
    console.log(drift ? `${drift} file(s) out of date — run node app/scripts/build_i18n.js` : 'i18n split is up to date');
    return drift ? 1 : 0;
  }
  console.log(drift ? `${drift} file(s) written` : 'nothing to do');
  return 0;
}

module.exports = { build, outputs, SRC, CORE, CHUNK_DIR, STRINGS_OPEN, STRINGS_CLOSE, SPLIT_LINE, CHUNKS_LINE };

if (require.main === module) process.exit(main(process.argv.slice(2)));
